version: '3.8'

services:
  simple-ntpd:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: simple-ntpd
    restart: unless-stopped
    ports:
      - "123:123/udp"
    volumes:
      - ./config:/etc/simple-ntpd:ro
      - ./logs:/var/log/simple-ntpd
    environment:
      - SIMPLE_NTPD_LISTEN_ADDRESS=0.0.0.0
      - SIMPLE_NTPD_LISTEN_PORT=123
      - SIMPLE_NTPD_STRATUM=2
      - SIMPLE_NTPD_LOG_LEVEL=INFO
    networks:
      - ntp-network
    healthcheck:
      test: ["CMD", "ntpdate", "-q", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ntp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
